### ISSUE TITLE
Use same URL scheme as package.elm-lang.org?

### ISSUE THREAD

**Issue by ianmackenzie** [dmy/elm-doc-preview#1]
Would it be possible to change the previewer to use the same URL scheme as package.elm-lang.org? For example, currently a module `Nested.Module` will have the path `#/Nested.Module` in the previewer where the official package site would use `Nested-Module`.

Making this change would presumably also allow putting anchors on individual types/functions/values, also to match the official package site (so that `Nested.Module.foo` would have the path `Nested-Module#foo`). Having both would mean that Markdown links to other functions/values/types in the same package would work the same way in the previewer as on the official package site, which would be very useful to be able to check.

**Comment by rlefevre** [comment]
I started like this but the problem is that I don't think that it's possible to put default routes with github pages. So refreshing the page from any module would lead to a 404. I think this would be really annoying. On the other hand, I would like to add anchors so I would like to find a solution that solve both issues. Any idea?

**Comment by rlefevre** [comment]
Using the URL scheme of the official site is not enough to make markdown links work because they trigger a full page refresh.

I will think more about it, but for now I don't see an easy fix.

**Comment by rlefevre** [comment]
The same URL scheme as package.elm-lang.org is now used and previews are stored in local storage to be able to re-open them at the correct  anchor after a page reload. This could be removed once https://github.com/elm-explorations/markdown/issues/1 is fixed.

**Comment by rlefevre** [comment]
For the record, markdown links are now intercepted from javascript to avoid page refreshes and add repos query parameters when needed.

Local storage is still used for local documentations as it helps navigating back from external links when testing a documentation.
