### ISSUE TITLE
Generate documentation for application source

### ISSUE THREAD

**Issue by domenkozar** [dmy/elm-doc-preview#17]
I have a couple of forked packages in my application, it would be great if I could browse those as well. Is there an elm limitation or it's just not implemented yet?

**Comment by rlefevre** [comment]
I don't think there is anything preventing this and I intend to implement it in the next release, but only for applications (this is most likely the main use cases of forked packages anyway).

What I had in mind is to search for `elm.json` files in all parent directories of `source-directories` and build their documentation if they are packages.

This would actually also allow to build an application documentation by organizing it in one or several sub-packages.

**Comment by domenkozar** [comment]
I see now https://github.com/elm/compiler/issues/1835. It's a bit of shame, but here we are.

Your approach sounds good to me!

**Comment by rlefevre** [comment]
Applications, including forked and local packages used with `source-directories` are now fully supported in 3.0.0-rc1 and later.
