### ISSUE TITLE
command-line output for use in automated tests

### ISSUE THREAD

**Issue by skyqrose** [dmy/elm-doc-preview#21]
I'd like to have my automated tests check that my docs are formatted well. If there are errors detected they're shown in the browser, and the checks done are more thorough than those done by the compiler. I'd like to be able to run the docs-previewer on the command line, see those errors there, and emit an exit code, without starting the webserver.

**Comment by rlefevre** [comment]
I'm not sure to understand. The checks done are exactly those done by the compiler run with:
```
elm make --docs=docs.json --report=json
```
Then `elm-doc-preview` renders the errors from the json report.
So you could use this command in your tests and get the same checks as the ones done with `elm-doc-preview`.

**Comment by skyqrose** [comment]
Ah, I didn't know about the `elm make --docs` flag. That satisfies my need. Thank you.

**Comment by rlefevre** [comment]
Ok, `elm make --help` can be useful then (it works for other `elm` commands too).
