### ISSUE TITLE
Add an option to check whether the documentation is correct

### ISSUE THREAD

**Issue by jfmengels** [dmy/elm-doc-preview#23]
Hi!

First of all, thanks for the awesome tool, I find it really useful!

One of the things I like about this tool, is that it tells us when the documentation is incomplete or erroneous, and it does that before we'd try to publish the package.

What I would like, is a way to enforce that the documentation is complete and valid when running the test suite. This way, when someone makes a pull request to your project, you don't have to manually run `elm-doc-preview` to verify that the docs are still okay. I think this can be especially useful for package repositories.

My proposal is to add a `--check` (or similarly named) option that doesn't run the documentation server, and only checks whether the docs are valid. If they are, the process succeeds, otherwise the process fails and the same errors as in the server are shown in the terminal.

Let me know what you think :)

**Comment by rlefevre** [comment]
`elm make --docs` will return an error exit code if the documentation is invalid, so you can use this command in your tests.

See https://github.com/dmy/elm-doc-preview/issues/21

**Comment by jfmengels** [comment]
Oh, awesome! Thanks a lot!
