### ISSUE TITLE
The doc server can't find `elm.json` in some folder structures

### ISSUE THREAD

**Issue by bengolds** [dmy/elm-doc-preview#26]
It appears the following line is assuming too much about the location of `elm.json`, and thus misses exposed modules in a lot of situation.
https://github.com/dmy/elm-doc-preview/blob/cf2c45b8896dc6d81c472971100a0f27fe393a5e/lib/elm-doc-server.ts#L292

**Comment by rlefevre** [comment]
Thank you.

Packages can only have their source in a `src` subdirectory, so this is fine for local/forked/vendor packages. However the application source can be anywhere, so the application exposed modules should not be detected again by this method but kept from its initial manifest.
