### ISSUE TITLE
works nicely

### ISSUE THREAD

**Issue by BKSpurgeon** [dmy/elm-doc-preview#29]
Hi there,

it works nicely. it looks very interesting too. thank you for providing this library.

regards

Ben

**Comment by rlefevre** [comment]
Thank you. Most people use it as a standalone tool, do you use it as a library?

**Comment by BKSpurgeon** [comment]
@rlefevre I am learning elm right now. I am not using it as a library just yet, because I am still trying to wrap my head around elm for the moment. 

I tried your library on the online preview that  you made. looks good. exactly like the elm docs. basic point is i am very appreciate of people who put their time and effort into writing things, as you have done.

best regards

Ben

**Comment by rlefevre** [comment]
Thank you very much @BKSpurgeon , this is much appreciated.

Try the npm version later, it has a lot more features than the online version. Also it looks like the docs because it uses the same library, so I didn't do much on this par (see the credits).

I hope you will enjoy Elm as much as I do.
