### ISSUE TITLE
Allow creating permalinks?

### ISSUE THREAD

**Issue by ianmackenzie** [dmy/elm-doc-preview#3]
Depending on how much you can do with Netlify's free tier, it would be really cool to have a "get permalink" button which would save the currently displayed docs to some sort of storage, then provide a permalink so that anyone else can view that documentation. This would be really helpful for sharing documentation snapshots on Slack etc. to get feedback on in-progress packages; currently the best approach is to upload README.md and docs.json to Slack and have others upload those to the previewer themselves.

**Comment by rlefevre** [comment]
I think that Netlify free tier is too limiting for that. But I have another idea, stay tuned...

**Comment by rlefevre** [comment]
The last version supports reading unpublished documentation from a github repo.
See https://elm-doc-preview.netlify.com/ for details.

This also allows to share links (to functions, types, ...) from the remote documentation.

Hopefully this answers this feature request, so I will close it. Feel free to reopen the issue if this does not help your use cases.

**Comment by ianmackenzie** [comment]
Very cool, clever solution!

**Comment by rlefevre** [comment]
Thank you for the feature request.

This solution works because GitHub allows CORS requests to raw text files. Hopefully this won't change...
