### ISSUE TITLE
Feature request: Generate docs.json, then exit

### ISSUE THREAD

**Issue by runarfu** [dmy/elm-doc-preview#30]
I'm currently using (or rather misusing) `elm-doc-preview` to generate a `docs.json` for my `application`, using an `elm-application.json` as suggested in the README. I'm starting up `elm-doc-preview` for the sole purpose of generating the `docs.json` file, retrieving it with `curl` and then stopping the server again. This doesn't play well with build scripts, and I would like `elm-doc-preview` to have a CLI flag that does this:

- Generate `docs.json` and write it to file
- Exit with 0 if it succeeds or something else if the `docs.json` couldn't be generated.

**Comment by rlefevre** [comment]
You can use `elm-doc-preview --output docs.json` (or `edp -o docs.json`) in version `4.0.0` to generate the documentation and exit with a status code.
