### ISSUE TITLE
Add a CLI option to check whether application documentation is correct

### ISSUE THREAD

**Issue by rjdellecese** [dmy/elm-doc-preview#31]
I'm using `elm-doc-preview` to generate application documentation, and would love a way to verify that my documentation is valid in CI. Just `elm make --docs` (per https://github.com/dmy/elm-doc-preview/issues/23 and https://github.com/dmy/elm-doc-preview/issues/21) doesn't seem to work to verify documentation correctness (or even to generate docs at all), which I assume is expected, given that my Elm code is an app and not a package.

Also, thank you for this awesome package!

**Comment by rlefevre** [comment]
I guess I will add an exit status for https://github.com/dmy/elm-doc-preview/issues/30, which should solve your issue too.

**Comment by rjdellecese** [comment]
I think that it would! Sorry, it seems I overlooked that that issue already proposes a solution to this.

**Comment by rjdellecese** [comment]
I guess the only thing I'd add, then, is that it might be nice to have the option to both receive an exit code and also _not_ generate a `docs.json` file. However, I think that either way, the exit code is the important bit.

**Comment by rlefevre** [comment]
Note that until then, you can make your own javascript script that use [elm-doc-preview API](https://github.com/dmy/elm-doc-preview#api) to start a server, download the [docs.json](https://github.com/dmy/elm-doc-preview#how-do-i-get-my-application-docsjson-file) from it, and exit with an error if the download failed or the docs are empty.

**Comment by rlefevre** [comment]
You can use `elm-doc-preview --output docs.json` (or `edp -o docs.json`) in version `4.0.0` to generate the documentation and exit with a status code.
