### ISSUE TITLE
cannot upload another .json after closing

### ISSUE THREAD

**Issue by CSchank** [dmy/elm-doc-preview#5]
If I make changes to my documentation and then "Close Preview", "Open Files" doesn't work again until the page is refreshed.

**Comment by rlefevre** [comment]
What do you mean by "If I make changes to my documentation", you mean you try to upload a modified `docs.json` file?

Also what do you mean by "it doesn't work", the file browsing window does not open? If so, dragging and dropping the modified documentation also does not work?

At last, do you have a more concrete example and some info about your browser, it could help.

Thanks

**Comment by CSchank** [comment]
You're right, apologies for that woefully inadequate bug report. Here are details:
1) I logged on to the previewer.
2) I selected my docs.json file. 
3) I could view the preview perfectly fine. 
4) I recompiled my docs.json with changes and clicked "Close Preview" on the app.
5) I then try to "Open Files" again to view the updated documentation. I select the file on the dialog but nothing changes in the app. It's as if no file was selected.
6) I refreshed the page and it seems to work again, but only once as before.

I have not tried dragging, I will when I get the chance. This was on Chrome 70 on a 2015 MacBook Pro running macOS High Sierra. Hopefully this is more helpful. Please let me know if you need more details from me.

**Comment by rlefevre** [comment]
Files handling have been rewritten in Elm using `elm/file`. I think this should solve this issue so I will close the bug. If you can still reproduce it, feel free to reopen.
