### ISSUE TITLE
Add self-host option

### ISSUE THREAD

**Issue by Y0hy0h** [dmy/elm-doc-preview#6]
This looks really useful. I would enjoy a local version via e. g. an npm package. I imagine it working by executing something like `npx elm-doc-preview` in the repository and it starting a server that I can access in my browser and that hot-reloads (#4) whenever I change my files.

I would prefer this over the online service, because I just want a quick preview. Running one command in the folder seems even simpler than importing files (that I would need to manually generate) into a website.

I don't know whether I can invest the time to open a PR for this, but I still want to pitch the idea.

**Comment by Y0hy0h** [comment]
I've just noticed the remark in the [Elm discourse post](https://discourse.elm-lang.org/t/elm-doc-preview-a-new-online-documentation-previewer/2001?u=y0hy0h) about this issue. So I added my rational for why I would prefer this.

**Comment by rlefevre** [comment]
This may not be clear, but this is what  https://github.com/dmy/elm-doc-preview/issues/4 is about, so I will close this one and add later some precisions.

Also this is in progress, and hopefully will be available very soon, so it might be preferable to not bother about submitting a PR right now.

**Comment by Y0hy0h** [comment]
Awesome, thanks a lot! :)

**Comment by rlefevre** [comment]
published as https://www.npmjs.com/package/elm-doc-preview
