### ISSUE TITLE
'Error: unsupported Elm version null' on Windows

### ISSUE THREAD

**Issue by ianmackenzie** [dmy/elm-doc-preview#7]
I installed `elm-doc-preview` on Windows 10 with

```
npm install -g elm-doc-preview
```

When trying to run in a package directory I get the following error message:

```
c:\Git\ianmackenzie\elm-units>elm-doc-preview
Error: unsupported Elm version null
0.19.0

c:\Git\ianmackenzie\elm-units>elm --version
0.19.0
```

If it makes a difference, I installed Elm itself using the Windows installer, not via NPM - so it's on my PATH, but if `elm-doc-preview` is looking for it specifically in some Node directories then it won't find it.

**Comment by rlefevre** [comment]
Thank you for the report.
I just tried with Windows 10 after having installed Elm with the official intaller from https://github.com/elm/compiler/releases but I cannot reproduce the issue yet:

```cmd
C:\Users\dmy\dev\elm-units>node --version
v10.14.2

C:\Users\dmy\dev\elm-units>elm-doc-preview --version
1.0.3

C:\Users\dmy\dev\elm-units>elm-doc-preview
elm-doc-preview 1.0.3 using elm 0.19.0
Previewing ianmackenzie/elm-units 1.0.0 from C:\Users\dmy\dev\elm-units
  |> building documentation
  |> watching elm.json, README.md and *.elm files
Browse <http://localhost:8000> to see your documentation
```
* What is your version of node.js?
* Did you use `cmd.exe` to run `elm-doc-preview` ?
* The `0.19.0` on the line after the error is suspect as `elm-doc-preview` should just print `Error: unsupported Elm version ${version}` and exits. Is it really part of the output? If so `elm` is found but the version string is somewhat corrupted.

**Comment by rlefevre** [comment]
I reproduced the issue with `node.js` 9.0.0 and `npm` 5.5.1, so you don't need to provide more information:

```
C:\Users\dmy\dev\elm-units>elm-doc-preview
Error: unsupported Elm version null
0.19.0

C:\Users\dmy\dev\elm-units>npm --version
5.5.1

C:\Users\dmy\dev\elm-units>node --version
v9.0.0
```

**Comment by rlefevre** [comment]
This should be fixed in elm-doc-preview@1.0.4.

**Comment by ianmackenzie** [comment]
Thanks, just tested with 1.0.6 and it does indeed work! I'm excited to go write some docs now =)

(Apologies for not including my Node/NPM versions in the initial report, that was dumb...)

**Comment by rlefevre** [comment]
Great! I would still advise to update your node.js version if you can, as `npx` is a convenient tool, and its incorrect way of running in your node version also slows down a little the start of `elm-doc-preview` (nothing that bad though). 

Note that you can also use `elm-doc-preview` during a package development, as it will display compilation errors too. So you can implement the package without building manually as it will detect modifications, recompile automatically, display errors if any, or documentation else.

Enjoy and thanks for the bug report.
